version: '3'
services:
  server:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - database
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
  database:
    image: mongo
    ports:
      - 27017:27017
