version: '3.8'
services:
  client:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000