version: '3'
services:
  client:
    image: dannyjialiliu/recipe-app-react
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000
  
  server:
    image: dannyjialiliu/recipe-app-node
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://mongo:27017/recipe-app

  mongo:
    image: mongo
    volumes:
      - .mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data: